apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: clusterclaims-controller
  name: clusterclaims-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      name: clusterclaims-controller
  template:
    metadata:
      labels:
        name: clusterclaims-controller
    spec:
      tolerations:
      - key: dedicated
        operator: Exists
        effect: NoSchedule
      - effect: NoSchedule 
        key: node-role.kubernetes.io/infra 
        operator: Exists
      serviceAccountName: clusterclaims-controller
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - "./manager-clusterclaims"
        - "-enable-leader-election"
        image: quay.io/jpacker/clusterclaims-controller:latest
        imagePullPolicy: Always
        name: clusterclaims-controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
          limits:
            cpu: "20m"
            memory: "500Mi"
          requests:
            cpu: "3m"
            memory: "65Mi"
      - command:
        - "./manager-clusterpools-delete"
        - "-enable-leader-election"
        image: quay.io/jpacker/clusterclaims-controller:latest
        imagePullPolicy: Always
        name: clusterpools-delete-controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
          limits:
            cpu: "20m"
            memory: "500Mi"
          requests:
            cpu: "3m"
            memory: "65Mi"
